#!/bin/sh
. "${HOME}/.cache/wal/colors.sh"

killall -q polybar

export color15_alpha="#ED${color15/'#'}"

wal -R &

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# panel
polybar bspwm-bar &

# Set some bsp specific stuff
bspc monitor -d I II III IV V VI VII VIII IX X

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc config window_gap 12
bspc config border_width 5

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
